name: "MagicPod Slack Notify"
description: "Slack notification"
inputs:
  API_TOKEN:
    description: "API Token"
    required: true
  ORGANIZATION:
    description: "Organization name"
    required: true
  PROJECT:
    description: "Project name"
    required: true
  INCOMING_WEBHOOK_URL:
    description: "Incoming Webhook URL"
    required: true
runs:
  using: "node16"
  main: "index.js"
